name: sawalker999
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43526
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Being Stephen Walker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbc3c6'
    - '#004564'
    - '#ffffff'
    - '#0284a8'
    - '#03cfe8'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
